# Generated by Django 5.1.7 on 2025-03-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tracker', '0002_remove_twitteruser_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_handle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
