# Generated by Django 5.1.7 on 2025-03-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tracker', '0003_twitteruser_wallet_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_url', models.URLField(help_text='Full Tweet URL')),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('like', 'Like'), ('retweet', 'Retweet'), ('comment', 'Comment')], max_length=10)),
                ('points_awarded', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_tracker.twitteruser')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_tracker.engagementtweet')),
            ],
            options={
                'unique_together': {('twitter_user', 'tweet', 'task_type')},
            },
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
