# Generated by Django 5.1.7 on 2025-03-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tracker', '0005_alter_twitteruser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_url', models.URLField(help_text='User-submitted Tweet URL', unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_tracker.twitteruser')),
            ],
        ),
    ]
