# Generated by Django 5.1.7 on 2025-03-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tracker', '0007_submittedtweet_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='has_completed_application',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('discord_handle', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('twitter_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='twitter_tracker.twitteruser')),
            ],
        ),
    ]
