# Generated by Django 5.1.7 on 2025-03-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tracker', '0008_twitteruser_has_completed_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='twitter_tracker.twitteruser'),
        ),
    ]
